In [1]:
vec = np.linspace(0, 10, num=25)
met = vec.reshape(5, 5)
print("Matrix met:\n", met)

NameError: name 'np' is not defined

In [ ]:
i = np.identity(3, dtype=float)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.random((3, 3))

array([[0.98834958, 0.51404359, 0.12169194],
       [0.47447447, 0.36169769, 0.62252226],
       [0.80363765, 0.0071747 , 0.27406177]])

In [ ]:
np.random.randint(0, 10, size=(5, 5))

array([[3, 6, 4, 1, 2],
       [7, 9, 4, 4, 4],
       [5, 8, 6, 8, 5],
       [6, 3, 8, 3, 1],
       [6, 9, 4, 3, 5]], dtype=int32)

In [ ]:
mat_1 = np.ones((3, 4))
mat_2 = np.zeros((5, 3))
np.savez('matrices.npz', ones_mat=mat_1, zeros_mat=mat_2)

In [ ]:
with np.load('matrices.npz') as file:
    ones_mat = file['ones_mat']
    zeros_mat = file['zeros_mat']
    
print("Loaded ones_mat:\n", ones_mat)
print("Loaded zeros_mat:\n", zeros_mat)

Loaded ones_mat:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Loaded zeros_mat:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
m1 =np.array([[1, 2, 3],
              [4, 5, 6]])
m2 =np.array([[7, 8, 9],
              [0, 0, 0]])
    mat_s = np.vstack((m1, m2))
    print("Stacked Matrix mat_s:\n", mat_s)

Stacked Matrix mat_s:
 [[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 0 0]]


In [ ]:
s = 4
v = np.array([1, 2, 3, 4])
v == s

array([False, False, False,  True])

In [ ]:
v1 = np.array([10, 6, 20, 4, 50])
v2 = np.array([10, 6, 25, 4, 50])
v1 == v2

array([ True,  True, False,  True,  True])

In [ ]:
v1 = np.array([10, 6, 20, 5, 50])
np.all(v1 >= 5)

np.True_

In [ ]:
v1 = np.array([10, 6, 20, 5, 50])
np.any(v1 > 30)

np.True_

In [ ]:
v1 = np.array([1, 2, 3, 4, 5])
v2 = np.array([2, 3, 0, 5, 3])
np.isclose(v1, v2, atol=1)

array([ True,  True, False,  True, False])

In [ ]:
v1 = np.array([1, 2, 3, 4, 5])
v2 = np.array([2, 3, 0, 5, 3])
np.allclose(v1, v2, atol=1)

False

In [ ]:
v = np.array([1, 2, 3, 4])
condition = v >= 4
new_arr = np.where(condition, -1, v)
print(condition)
print(new_arr)

[False False False  True]
[ 1  2  3 -1]


In [ ]:
pip install pandas

   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
    --------------------------------------- 0.3/11.0 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.0 MB 1.5 MB/s eta 0:00:07
   -- ------------------------------------- 0.8/11.0 MB 1.6 MB/s eta 0:00:07
   ---- ----------------------------------- 1.3/11.0 MB 1.5 MB/s eta 0:00:07
   ----- ---------------------------------- 1.6/11.0 MB 1.5 MB/s eta 0:00:07
   ------ --------------------------------- 1.8/11.0 MB 1.5 MB/s eta 0:00:06
   -------- ------------------------------- 2.4/11.0 MB 1.6 MB/s eta 0:00:06
   --------- ------------------------------ 2.6/11.0 MB 1.5 MB/s eta 0:00:06
   ---------- ----------------------------- 2.9/11.0 MB 1.6 MB/s eta 0:00:06
   ------------ --------------------------- 3.4/11.0 MB 1.6 MB/s eta 0:00:05
   ------------- -------------------------- 3.7/11.0 MB 1.6 MB/s eta 0:00:05
   --------------- -

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('test.csv')
df.head()


Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  
0  2011  
1  2011  
2  2011  
3  2011  
4  2011

In [4]:
df.tail()

Id  EmployeeName                            JobTitle    BasePay  \
35  36    KHOA TRINH   ELECTRONIC MAINTENANCE TECHNICIAN  101953.20   
36  37  SUSAN CURRIN  ADMINISTRATOR, SFGH MEDICAL CENTER  245124.44   
37  38   JAMES BOSCH  INSPECTOR III, (POLICE DEPARTMENT)  110661.20   
38  39    JONES WONG  LIEUTENANT III (POLICE DEPARTMENT)  132202.26   
39  40  BRENDAN WARD  BATTALION CHIEF, (FIRE DEPARTMENT)  147158.85   

    OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  
35    139102.95   16483.94       NaN  257540.09         257540.09  2011  
36         0.00   12000.00       NaN  257124.44         257124.44  2011  
37     31162.04  111446.20       NaN  253269.44         253269.44  2011  
38     52648.92   67083.83       NaN  251935.01         251935.01  2011  
39     64985.85   39540.46       NaN  251685.16         251685.16  2011

In [5]:
s = pd.Series([1, 2, 3], index=["A","B","C"])
s

A    1
B    2
C    3
dtype: int64

In [6]:
data =[[1,444,'abc'],
       [2,555,'def'],
       [3,666,'ghi'],
       [4,777,'xyz']]
    
df = pd.DataFrame(data, columns=["Index","ID","Name"])
display(df)

Index   ID Name
0      1  444  abc
1      2  555  def
2      3  666  ghi
3      4  777  xyz

In [7]:
df.dtypes

Index     int64
ID        int64
Name     object
dtype: object

In [8]:
df["ID"] = df["ID"].astype("category")
df.dtypes

Index       int64
ID       category
Name       object
dtype: object

In [9]:
cols =['Index','ID']
df[cols] = df[cols].astype(int)
df.dtypes

Index     int64
ID        int64
Name     object
dtype: object

In [10]:
df.describe()

Index          ID
count  4.000000    4.000000
mean   2.500000  610.500000
std    1.290994  143.300384
min    1.000000  444.000000
25%    1.750000  527.250000
50%    2.500000  610.500000
75%    3.250000  693.750000
max    4.000000  777.000000

In [11]:
data =[[1,444,'abc'],
       [2,555,'def'],
       [3,666,'ghi'],
       [4,777,'xyz']]
    
df[cols] = df[cols].astype("category")

df = pd.DataFrame(data, columns=["Index","ID","Name"])
df.describe()

Index          ID
count  4.000000    4.000000
mean   2.500000  610.500000
std    1.290994  143.300384
min    1.000000  444.000000
25%    1.750000  527.250000
50%    2.500000  610.500000
75%    3.250000  693.750000
max    4.000000  777.000000

In [12]:
df['ID'].unique()

array([444, 555, 666, 777])

In [13]:
df['ID'].nunique()

4

In [14]:
df.columns

Index(['Index', 'ID', 'Name'], dtype='object')

In [15]:
df['ID'].max()

np.int64(777)

In [16]:
df.info()    

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Index   4 non-null      int64 
 1   ID      4 non-null      int64 
 2   Name    4 non-null      object
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes


In [17]:
d = df['ID'].value_counts()
d

ID
444    1
555    1
666    1
777    1
Name: count, dtype: int64

In [18]:
df['ID'].sum()

np.int64(2442)

In [19]:
df.max()

Index      4
ID       777
Name     xyz
dtype: object

In [20]:
df['ID'].values

array([444, 555, 666, 777])

In [21]:
df.replace(666, 333)

Index   ID Name
0      1  444  abc
1      2  555  def
2      3  333  ghi
3      4  777  xyz

In [22]:
df.replace({333:666,777:888})

Index   ID Name
0      1  444  abc
1      2  555  def
2      3  666  ghi
3      4  888  xyz

In [23]:
def dupliecated(x):
    return x*2

df['ID'].apply(dupliecated)

0     888
1    1110
2    1332
3    1554
Name: ID, dtype: int64

In [24]:
df['ID'].apply(lambda x: x * 2)

0     888
1    1110
2    1332
3    1554
Name: ID, dtype: int64

In [25]:
df.Index.iloc[2]

np.int64(3)

In [26]:
df.iloc[2,1]

np.int64(666)

In [27]:
df.iloc[:, 0:2]

Index   ID
0      1  444
1      2  555
2      3  666
3      4  777

In [28]:
df['new_col'] = df.Name + df.Name
df
#df.insert(3,"new",new_col)

Index   ID Name new_col
0      1  444  abc  abcabc
1      2  555  def  defdef
2      3  666  ghi  ghighi
3      4  777  xyz  xyzxyz

In [29]:
df.drop('new_col' ,axis=1)


Index   ID Name
0      1  444  abc
1      2  555  def
2      3  666  ghi
3      4  777  xyz

In [30]:
new_row = {"Index":'99',"ID":'9', "Name":"welcome"}
df = pd.concat([df, pd.DataFrame(new_row, index=[0])],ignore_index=True)
df

Index   ID     Name new_col
0     1  444      abc  abcabc
1     2  555      def  defdef
2     3  666      ghi  ghighi
3     4  777      xyz  xyzxyz
4    99    9  welcome     NaN

In [31]:
null = df.isnull()
pd.DataFrame(null.sum()).T

Index  ID  Name  new_col
0      0   0     0        1

In [36]:
df

Index   ID     Name new_col
0     1  444      abc  abcabc
1     2  555      def  defdef
2     3  666      ghi  ghighi
3     4  777      xyz  xyzxyz
4    99    9  welcome     NaN