# NumPy Programming Assignment

Part 1: Smart Array Factory
Task: Create a function that allows students to generate specific array types quickly using built-in NumPy methods.


In [1]:
import numpy as np

def array_factory(mode, shape, value=None):
    """
    Creates various NumPy arrays based on the mode.
    - 'zeros': Array filled with 0.
    - 'ones': Array filled with 1.
    - 'full': Array filled with a specified 'value'.
    - 'identity': A square identity matrix of size 'shape'.
    """

    if mode == 'zeros':
        return np.zeros(shape)

    elif mode == 'ones':
        return np.ones(shape)

    elif mode == 'full':
        if value is None:
            raise ValueError("You must provide a value for 'full' mode")
        return np.full(shape, value)

    elif mode == 'identity':
        return np.eye(shape)

    else:
        raise ValueError("Invalid mode. Use 'zeros', 'ones', 'full', or 'identity'")


In [3]:
print("Zeros array:")
print(array_factory('zeros', (2, 3)))
print("Ones array:")
print(array_factory('ones', (3, 3)))
print("Full array:")
print(array_factory('full', (2, 2), 7))
print("Identity matrix:")
print(array_factory('identity', 4))

Zeros array:
[[0. 0. 0.]
 [0. 0. 0.]]
Ones array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Full array:
[[7 7]
 [7 7]]
Identity matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Part 2: The secure_reshape_and_stack Function.

This function demonstrates how to handle data integration by transforming a flat data structure into a matrix and then combining it with an existing dataset

In [4]:
import numpy as np

def secure_reshape_and_stack(data1, data2, new_shape):
    """
    1. Validates and converts inputs to NumPy arrays.
    2. Reshapes the first dataset to a specific dimension.
    3. Vertically stacks both datasets into one matrix.
    """
    try:
        # Convert inputs to ndarray
        arr1 = np.array(data1)
        arr2 = np.array(data2)

        # Reshape arr1 to the new shape
        reshaped_arr1 = arr1.reshape(new_shape)

        # Vertically stack both arrays
        combined_dataset = np.vstack((reshaped_arr1, arr2))

        return combined_dataset

    except ValueError as e:
        # Handle reshape or stacking errors
        raise ValueError(f"Company-grade Error: {e}")


In [5]:
data1 = [1, 2, 3, 4]
data2 = [[5, 6], [7, 8]]

result = secure_reshape_and_stack(data1, data2, (2, 2))
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


part-3 The apply_threshold Function.

This function demonstrates Conditional Access and Modification, which are primarily used in data cleaning and processing. It follows the logic of identifying specific elements based on a boolean condition and replacing them efficiently.

In [9]:
import numpy as np

def apply_threshold(arr, threshold, replacement_value=-1):
    """
    Finds elements satisfying a condition (>= threshold) 
    and replaces them with a new value.
    """
    # 1. Convert input to a numpy array
    arr = np.array(arr)

    # 2. Define the condition (Boolean array)
    condition = arr >= threshold

    # 3. Apply modification using np.where
    modified_arr = np.where(condition, replacement_value, arr)

    return modified_arr


In [10]:
v = np.array([1, 2, 3])
result = apply_threshold(v, 2, -20)
print(result)


[  1 -20 -20]


TestCase

In [12]:
# Regional Branch A (Flat sales data)
branch_a = [1, 2, 3, 4, 5, 6] 

# Regional Branch B (Already formatted 2x3 matrix)
branch_b = [[7, 8, 9], 
            [10, 11, 12]]

# Reshape A to 2x3 and stack with B
final_report = secure_reshape_and_stack(branch_a, branch_b, (2, 3))
print(final_report)
# Resulting shape: (4, 3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
