In [61]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [62]:
import numpy as np

In [63]:
v1 = np.array([10, 6, 20, 4, 50])
v2 = np.array([5, 15, 25, 35, 45])
print(v1)
print(v2)
print("Addition:", v1 + v2)
print("Subtraction:", v1 - v2)
print("Multiplication:", v1 * 5)
print("Dot Product:", v1.dot(v2))

[10  6 20  4 50]
[ 5 15 25 35 45]
Addition: [15 21 45 39 95]
Subtraction: [  5  -9  -5 -31   5]
Multiplication: [ 50  30 100  20 250]
Dot Product: 3030


In [64]:
m1 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])
print("Matrix m1:\n", m1)
print("=============================")
m2 = np.array([[0, 2, 3],
               [8, 15, 6],        
               [7, 8, 2]])
print("Matrix m2:\n", m2)
print("=============================")

print("Addition:\n", m1 + m2)
print("=============================")
print("Dot Product:\n", m1.dot(m2))

Matrix m1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix m2:
 [[ 0  2  3]
 [ 8 15  6]
 [ 7  8  2]]
Addition:
 [[ 1  4  6]
 [12 20 12]
 [14 16 11]]
Dot Product:
 [[ 37  56  21]
 [ 82 131  54]
 [127 206  87]]


In [65]:
s = np.array(5)
print("s Dimensions:", s.ndim)
print("s Shape:", s.shape)

s Dimensions: 0
s Shape: ()


In [66]:
s2 = np.array([5, 10, 15])
print("s2 Dimensions:", s2.ndim) 
print("s2 Shape:", s2.shape)

s2 Dimensions: 1
s2 Shape: (3,)


In [67]:
s3 = np.array([[1, 2, 3],
               [2, 5, 7],
               [9, 8, 7]])
print("s3 Dimensions:", s3.ndim)
print("s3 Shape:", s3.shape)

s3 Dimensions: 2
s3 Shape: (3, 3)


In [68]:
class Student:
    def __init__(self, name):
        self.name = name
    @property    
    def display(self):
        print(f"Name: {self.name}")

In [69]:
s1 = Student("Ahmed")
s1.display
s1.name 

Name: Ahmed


'Ahmed'

In [70]:
vec_1 = np.array([1, 2, 3, 4, 5, 6])
mat_1 = vec_1.reshape(3, 2)
print("Matrix mat_1:\n", mat_1)

Matrix mat_1:
 [[1 2]
 [3 4]
 [5 6]]


In [71]:
def reshape_mat(vector, rows, cols):
    if len(vector) != rows * cols:
        raise ValueError("The size of the vector does not match the specified dimensions.")
    return vector.reshape(rows, cols)

reshaped_mat = reshape_mat(vec_1, 3, 2)
print("Reshaped Matrix:\n", reshaped_mat)

Reshaped Matrix:
 [[1 2]
 [3 4]
 [5 6]]


In [72]:
vec_2 = np.array([1, 2, 3, 4])
vec_2.shape[0]

4

In [73]:
vec_2 = np.array([1, 2, 3, 4])
mat_2 = vec_2.reshape(vec_2.shape[0], 1)
print("Matrix mat_2:\n", mat_2)

Matrix mat_2:
 [[1]
 [2]
 [3]
 [4]]


In [74]:
def reshape_mat2(mat):
    mat = mat.reshape(mat.shape[0], 1)
    return mat

reshape_mat2 = reshape_mat2(vec_2)
print("Reshaped Matrix mat_2:\n", reshape_mat2)

Reshaped Matrix mat_2:
 [[1]
 [2]
 [3]
 [4]]


In [75]:
vec_3 = np.array([1, 2, 3, 4, 5, 6])
mat_3 = vec_3[:,None]
print("Matrix mat_3:\n", mat_3)

Matrix mat_3:
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [76]:
mat_4 = np.array([[1.1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print("Matrix mat_4 Type:", mat_4.dtype)
print("Matrix mat_4:\n", mat_4)


Matrix mat_4 Type: float64
Matrix mat_4:
 [[1.1 2.  3. ]
 [4.  5.  6. ]
 [7.  8.  9. ]]


In [77]:
mat_5 = np.array([[True, False, True],
                 [True, True, False]])
print("Matrix mat_5 Type:", mat_5.dtype)
print("Matrix mat_5:\n", mat_5)


Matrix mat_5 Type: bool
Matrix mat_5:
 [[ True False  True]
 [ True  True False]]


In [78]:
class C:
    x = 3
o1 = C()

In [79]:
mat_6 = np.array([[1, '2', 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print("Matrix mat_ Type:", mat_.dtype)
print("Matrix mat_:\n", mat_)

Matrix mat_ Type: <U21
Matrix mat_:
 [['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']]


In [80]:
f_mat = mat_6.astype(float)
print("Matrix f_mat Type:", f_mat.dtype)
print("Matrix f_mat:\n", f_mat)

Matrix f_mat Type: float64
Matrix f_mat:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [60]:
f_mat[1, 2]


np.float64(6.0)

In [ ]:
x1 = np.array([1, 2, 3, 4, 5])
print(x1[0])
print(x1[-3:-1])

1


array([3, 4])

In [91]:
mat_5 = np.array([[1, 2, 3],
                  [4, 5, 6],    
                  [7, 8, 9],
                  [0, 0, 0]])
print("Matrix mat_5:\n", mat_5[1:3,0:2])
print("Matrix mat_5:\n", mat_5[-3:-1,-3:-1])

print("Transpose of mat_5:\n", mat_5.T)


Matrix mat_5:
 [[4 5]
 [7 8]]
Matrix mat_5:
 [[4 5]
 [7 8]]
Transpose of mat_5:
 [[1 4 7 0]
 [2 5 8 0]
 [3 6 9 0]]


In [92]:
mat_6 = np.zeros((3,4))
print("Matrix mat_6:\n", mat_6)

Matrix mat_6:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [93]:
mat_7 = np.ones((3,4))
print("Matrix mat_7:\n", mat_7)

Matrix mat_7:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [94]:
mat_8 = np.full((3,3),4)
print("Matrix mat_8:\n", mat_8)

Matrix mat_8:
 [[4 4 4]
 [4 4 4]
 [4 4 4]]


In [98]:
mat_9 = np.empty((3,3))
print("Matrix mat_9:\n", mat_9)

Matrix mat_9:
 [[1.1 2.  3. ]
 [4.  5.  6. ]
 [7.  8.  9. ]]


In [99]:
mat_10 = np.arange(0, 361, 90)
print("Matrix mat_10:\n", mat_10)

Matrix mat_10:
 [  0  90 180 270 360]


In [104]:
vec_4 = np.linspace(0, 10, num=10)
print("Vector vec_4:\n", vec_4)

Vector vec_4:
 [ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
